var sortStyle={
    "1":{
        className:"icon_1",
        img:"icon_1.jpg"
    },
    "2":{
        className:"icon_2",
        img:"icon_2.jpg"
    },
    "3":{
        className:"icon_3",
        img:"icon_3.jpg"
    },
    "4":{
        className:"icon_4",
        img:"icon_4.jpg"
    },
    "5":{
        className:"icon_5",
        img:"icon_5.jpg"
    },
    "6":{
        className:"icon_6",
        img:"icon_6.jpg"
    },
    "7":{
        className:"icon_7",
        img:"icon_7.jpg"
    }
}